### ISSUE TITLE
Error in plugin "gulp-execa"

### ISSUE THREAD

**Issue by franckadil** [ehmicky/gulp-execa#4]
Hi,

I am having a test and build error when running gulp-execa on Arch Linux:

```
src/preload.js → app/preload.js...
[!] Error: Could not resolve './preload/spellChecking' from src/preload.js
Error: Could not resolve './preload/spellChecking' from src/preload.js
    at error (/home/franck/Documents/Development/Build/Rocket.Chat.Electron/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at ModuleLoader.handleResolveId (/home/franck/Documents/Development/Build/Rocket.Chat.Electronnode_modules/rollup/dist/shared/node-entry.js:12389:24)
    at ModuleLoader.<anonymous> (/home/franck/Documents/Development/Build/Rocket.Chat.Electron/node_modules/rollup/dist/shared/node-entry.js:12277:30)
    at Generator.next (<anonymous>)
    at fulfilled (/home/franck/Documents/Development/Build/Rocket.Chat.Electron/node_modules/rollup/dist/shared/node-entry.js:38:28)

[00:36:35] 'build:bundle' errored after 5.14 s
[00:36:35] Error in plugin "gulp-execa"
Message:
    Command failed with exit code 1: rollup -c
Stack:
Error: Command failed with exit code 1: rollup -c
    at makeError (/home/franck/Documents/Development/Build/Rocket.Chat.Electron/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/home/franck/Documents/Development/Build/Rocket.Chat.Electron/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
[00:36:35] 'build' errored after 5.15 s
[00:36:35] 'start' errored after 5.15 s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```
Execa works fine on Mac OSX and Windows 10, it seems to be related only to linux.

Thanks for looking into this,
Kind regards

**Comment by franckadil** [comment]
I apologize the issue was related to a file naming convention, Linux is case sensitive.

**Comment by ehmicky** [comment]
Hi @franckadil, thanks for reaching out and explaining what went wrong.
Feel free to post any other issues you might encounter.
